name = "hesabyar"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hesabyar"
database_id = "f8f70b1f-372b-4d2d-b3c2-1c02e95fd0a5"
