name = "hesabyar"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hesabyar"
database_id = "7e883752-9059-42e7-90b5-12e5d0888a9d"

[observability.logs]
enabled = true
invocation_logs = true

