name = "hesabyar"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hesabyar"
database_id = "26be07a9-62f4-4736-a14e-32f2176e40de"

[observability.logs]
enabled = true
invocation_logs = true
